version: '3'
services:
  headofcontent-de:
    image: headofcontent.de:${IMAGE_VERSION}
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - '3000:3000'
